name: paper-trader
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pandas
  - numpy
  - scikit-learn
  - xgboost
  - yfinance
  - matplotlib
  - mplfinance
  - ta-lib
  - pyyaml
  - pip
  - pip:
    - python-dotenv
    - schedule
    - pandas-datareader
